name: build swift5.9.2

on:
  workflow_dispatch:
  push:
    branches: [swift-5.9.2-RELEASE]
 
jobs:
  build:
    runs-on: macos-14
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    steps: 
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        shell: bash
        run: |
          brew install cmake
          brew install ninja
      
      - name: Install setuptools for distutils
        run: |
          python3 -m ensurepip
          python3 -m pip install --upgrade pip setuptools
          
      - name: Set Environment Variables
        run: echo "SKIP_XCODE_VERSION_CHECK=1" >> $GITHUB_ENV

      - name: Clone Hikari-Swift Repository
        run: |
          git clone --recurse-submodules -b swift-5.9.2-RELEASE https://github.com/61bcdefg/Hikari-Swift.git ~/Downloads/Hikari-Swift

      - name: Build Hikari Swift Toolchain
        run: |
          cd ~/Downloads/Hikari-Swift/
          ./swift/utils/build-toolchain Hikari

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Hikari_Swift5.9.2-2024-11-22-a-osx.tar.gz
          path: /Users/runner/Downloads/Hikari-Swift/Hikari_Swift5.9.2-2024-11-22-a-osx.tar.gz 
